# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_auto_20170312_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='leixing',
            field=models.IntegerField(choices=[(1, 'SC'), (2, 'MC'), (3, 'Priority Order')], default=1),
        ),
    ]
