# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_auto_20170327_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfenshu',
            name='right_question',
            field=models.ManyToManyField(related_name='right_question', to='quizapp.Question'),
        ),
    ]
