# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_auto_20170327_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfenshu',
            name='right_question',
        ),
    ]
