# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0007_remove_userfenshu_right_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfenshu',
            name='zhangjie',
            field=models.CharField(default='', max_length=100),
        ),
    ]
